format = "$directory$git_branch$git_status$python$kubernetes\n$character"
add_newline = false

[directory]
truncation_length = 3

[git_branch]
symbol = " "

[kubernetes]
disabled = false
format = " ☸ [$context](blue)"

[python]
format = "[\\($virtualenv\\)]($style) "

[character]
success_symbol = "[\uf0a9](bold green) "
error_symbol = "[\uf0a9](bold red) "
