# Key lag
set -s escape-time 1

# Scrolling through terminal history
set -g mouse on
set -g history-limit 50000

# vi keys in copy/choose mode.
set -g mode-keys vi
set -g status-keys vi

# Pane navigation (Up/Down)
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-h select-pane -L
bind-key -n M-l select-pane -R

# Window navigation (Left/Right)
bind-key -n M-H previous-window
bind-key -n M-L next-window

# Status bar
set -g status-style bg=#191724,fg=#e0def4
set -g window-status-style bg=#191724,fg=#e0def4
set -g window-status-current-style fg=#c4a7e7,bg=#191724,bold

# Split-pane borders
set -g pane-border-style fg=#26233a
set -g pane-active-border-style fg=#31748f

# Stay in same dir
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind c new-window -c "#{pane_current_path}"
